#pragma once

#include <any>
#include <map>
#include <mutex>
#include <ctime>
#include <regex>
#include <queue>
#include <tuple>
#include <vector>
#include <thread>
#include <future>
#include <string>
#include <memory>
#include <chrono>
#include <limits>
#include <format>
#include <random>
#include <variant>
#include <sstream>
#include <iomanip>
#include <fstream>
#include <cstdint>
#include <cassert>
#include <cstddef>
#include <iostream>
#include <typeindex>
#include <optional>
#include <windows.h>
#include <algorithm>
#include <functional>
#include <shellapi.h>
#include <filesystem>
#include <type_traits>
#include <string_view>
#include <shared_mutex>
#include <unordered_map>
#include <unordered_set>
#include <condition_variable>
